# Generated by Django 3.1.6 on 2021-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attribute_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attribute_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attribute_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
